# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: kcl
day_night: true
font: kcl
font_size: M

# SEO

site_type: Organization
local_business_type: ''
org_name: 'King''s College London'
description: My research group description.
twitter: ''

# Contact (edit or remove options as required)

email: ''
phone: +44 (0)20 7836 5454
address:
  street: (N)6.11, Bush House, 30 Aldwych
  city: London
  # region: CA
  postcode: 'WC2B 4BG'
  country: United Kingdom
  country_code: GB
coordinates:
  latitude: '51.51275'
  longitude: '-0.117278'
directions: ''
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
appointment_url: ''
contact_links:
 - icon: twitter
   icon_pack: fab
   name: Our tweets
   link: 'https://twitter.com/kclinformatics'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-gb

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: false
  allow_commercial: false
  notice: '© 2021 King''s College London'
# i_am_a_sponsor: true
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
